version: '3.6'
services:
  api1: 
    container_name: ribon-game-api1
    image: ribon-game-api1
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3000"
    environment:
      - NUMBERSERVER=1
    volumes:
      - ./backend/:/usr/app
    depends_on:
      - "mongo"
  api2: 
    container_name: ribon-game-api2
    image: ribon-game-api2
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3000"
    environment:
      - NUMBERSERVER=2
    volumes:
      - ./backend/:/usr/app
    depends_on:
      - "mongo"
  api3: 
    container_name: ribon-game-api3
    image: ribon-game-api3
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3000"
    environment:
      - NUMBERSERVER=3
    volumes:
      - ./backend/:/usr/app
    depends_on:
      - "mongo"
  mongo:
    container_name: ribon-game-mongo
    image: mongo
    ports:
      - "27017:27017"
  # adminmongo:
  #   container_name: ribon-game-mongo-admin
  #   image: "mrvautin/adminmongo"
  #   ports:
  #     - "1234:1234"
  nginx:
    container_name: ribon-game-load-balancer
    image: ribon-game-load-balancer
    build:
      context: ./load-balancer
      dockerfile: Dockerfile-lb
    ports:
      - "80:80"
    links:
      - api1:api1
      - api2:api2
      - api3:api3
